### ISSUE TITLE
CSS preview not open

### ISSUE THREAD

**Issue by menitasa** [sandorengholm/csspreview#3]

**Comment by nonkit** [comment]
After selecting "CSS Preview" in command palette, CSS Preview window never comes up.

CSS Preview: v1.0.2
OS: Windows 10 Home
VSCode:
Version: 1.46.0 (system setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:44.937Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 10.0.18362

**Comment by sandorengholm** [comment]
The extension has now been updated to v1.0.3 and works again, please try to update the extension 👍

**Comment by nonkit** [comment]
I confirmed v1.0.3 shows CSS Preview.  Thanks.
