### ISSUE TITLE
It does not work, it does not show the window.

### ISSUE THREAD

**Issue by COD3BREAK3R** [sandorengholm/csspreview#4]
The extension does not work

**Comment by taggar** [comment]
Same here ...

Visual Studio Code Version: 1.36.1 on Ubuntu 10.04.2 LTS
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-25-generic

**Comment by sandorengholm** [comment]
The extension has now been updated an is working again in the vscode ^1.46.0
