### ISSUE TITLE
--text property doesn't show text in preview

### ISSUE THREAD

**Issue by nonkit** [sandorengholm/csspreview#5]
--text property doesn't show the text in css preview.

Sample code:
```
.box {
    height: 150px;
    width: 50%;
    border-radius: 10px;
    text-align: center;
    line-height: 150px;
    --text: "Enjoy!";
}
```
OS: Windows 10 Home
VSCode: 1.46.0
CSS Preview: 1.0.3

**Comment by sandorengholm** [comment]
Hi Nonkit,
Thank you for your feedback!

I've upgraded the extension to 1.0.4 where i've replaced the --text property with a --content property where you're able to do even more than before. Now you can insert html markup and make even more complex previews.

Please test it out and let me know if i've pushed that 3 star rating to a 5 this time around :)

Best regards
Sandor Engholm

**Comment by nonkit** [comment]
I confirmed --content property works well with CSS Preview 1.0.4.  Thanks.

Sample code:
```
.box {
    height: 150px;
    width: 50%;
    border-radius: 10px;
    text-align: center;
    line-height: 150px;
    --content:
        <p>"Enjoy!"</p>;
}
```

**Comment by sandorengholm** [comment]
Awesome, thank you for testing it out! 👍
